### ISSUE TITLE
blockstack tagline update

### ISSUE THREAD

**Issue by guylepage3** [blockstack/community#19]
Hey everyone I'd like to propose a new tagline discussion. Something that is inspirational, mysterious and evokes a sense of never ending purpose.

Here is one that I would like to propose:
- live the future. be the future.

This was inspired by Apple's 1984 commercial and release that put them on the map.
![1984-commercial-ending](https://cloud.githubusercontent.com/assets/1711854/18230984/6b7c7286-7279-11e6-97ec-8c900caab033.jpg)

**Comment by shea256** [comment]
Hm, not really doing it for me. What are you trying to accomplish?

**Comment by guylepage3** [comment]
Intension was to devise a tagline that is mysterious, evoke a sense of comradery, and something devs can rally behind. Not saying that that's the tagline.. But it is something that makes me feel like something is happening.

**Comment by shea256** [comment]
Declare your sovereignty. Be part of the free Internet.

Freedom and prosperity. The new, decentralized Internet.

**Comment by shea256** [comment]
Here's one of the most famous writings from the early hacker days:
https://www.eff.org/cyberspace-independence

> Governments of the Industrial World, you weary giants of flesh and steel, I come from Cyberspace, the new home of Mind. On behalf of the future, I ask you of the past to leave us alone. You are not welcome among us. You have no sovereignty where we gather...
> 
> We have no elected government, nor are we likely to have one, so I address you with no greater authority than that with which liberty itself always speaks. I declare the global social space we are building to be naturally independent of the tyrannies you seek to impose on us. You have no moral right to rule us nor do you possess any methods of enforcement we have true reason to fear.
> 
> Governments derive their just powers from the consent of the governed. You have neither solicited nor received ours. We did not invite you. You do not know us, nor do you know our world. Cyberspace does not lie within your borders. Do not think that you can build it, as though it were a public construction project. You cannot. It is an act of nature and it grows itself through our collective actions.
> 
> You have not engaged in our great and gathering conversation, nor did you create the wealth of our marketplaces. You do not know our culture, our ethics, or the unwritten codes that already provide our society more order than could be obtained by any of your impositions.
> 
> You claim there are problems among us that you need to solve. You use this claim as an excuse to invade our precincts. Many of these problems don't exist. Where there are real conflicts, where there are wrongs, we will identify them and address them by our means. We are forming our own Social Contract. This governance will arise according to the conditions of our world, not yours. Our world is different.
> 
> Cyberspace consists of transactions, relationships, and thought itself, arrayed like a standing wave in the web of our communications. Ours is a world that is both everywhere and nowhere, but it is not where bodies live.
> 
> We are creating a world that all may enter without privilege or prejudice accorded by race, economic power, military force, or station of birth.
> 
> We are creating a world where anyone, anywhere may express his or her beliefs, no matter how singular, without fear of being coerced into silence or conformity.
> 
> Your legal concepts of property, expression, identity, movement, and context do not apply to us. They are all based on matter, and there is no matter here.
> 
> Our identities have no bodies, so, unlike you, we cannot obtain order by physical coercion. We believe that from ethics, enlightened self-interest, and the commonweal, our governance will emerge. Our identities may be distributed across many of your jurisdictions. The only law that all our constituent cultures would generally recognize is the Golden Rule. We hope we will be able to build our particular solutions on that basis. But we cannot accept the solutions you are attempting to impose.
> 
> In the United States, you have today created a law, the Telecommunications Reform Act, which repudiates your own Constitution and insults the dreams of Jefferson, Washington, Mill, Madison, DeToqueville, and Brandeis. These dreams must now be born anew in us.
> 
> You are terrified of your own children, since they are natives in a world where you will always be immigrants. Because you fear them, you entrust your bureaucracies with the parental responsibilities you are too cowardly to confront yourselves. In our world, all the sentiments and expressions of humanity, from the debasing to the angelic, are parts of a seamless whole, the global conversation of bits. We cannot separate the air that chokes from the air upon which wings beat.
> 
> In China, Germany, France, Russia, Singapore, Italy and the United States, you are trying to ward off the virus of liberty by erecting guard posts at the frontiers of Cyberspace. These may keep out the contagion for a small time, but they will not work in a world that will soon be blanketed in bit-bearing media.
> 
> Your increasingly obsolete information industries would perpetuate themselves by proposing laws, in America and elsewhere, that claim to own speech itself throughout the world. These laws would declare ideas to be another industrial product, no more noble than pig iron. In our world, whatever the human mind may create can be reproduced and distributed infinitely at no cost. The global conveyance of thought no longer requires your factories to accomplish.
> 
> These increasingly hostile and colonial measures place us in the same position as those previous lovers of freedom and self-determination who had to reject the authorities of distant, uninformed powers. We must declare our virtual selves immune to your sovereignty, even as we continue to consent to your rule over our bodies. We will spread ourselves across the Planet so that no one can arrest our thoughts.
> 
> We will create a civilization of the Mind in Cyberspace. May it be more humane and fair than the world your governments have made before.
> 
> Davos, Switzerland
> February 8, 1996

**Comment by shea256** [comment]
Quotes from http://www.economist.com/node/16941635

> THE first internet boom, a decade and a half ago, resembled a religious movement.
> 
> Omnipresent cyber-gurus ... prophesied a digital paradise in which not only would commerce be frictionless and growth exponential, but democracy would be direct and the nation-state would no longer exist.
> 
> The internet was a wide-open space, a new frontier. For the first time, anyone could communicate electronically with anyone else—globally and essentially free of charge. Anyone was able to create a website or an online shop, which could be reached from anywhere in the world using a simple piece of software called a browser, without asking anyone else for permission. The control of information, opinion and commerce by governments—or big companies, for that matter—indeed appeared to be a thing of the past.
> 
> “We're heading into a war for control of the web,” Tim O'Reilly, an internet savant who heads O'Reilly Media, a publishing house, wrote late last year. “And in the end, it's more than that, it's a war against the web as an interoperable platform.”

**Comment by larrysalibra** [comment]
Declare independence. Build the free Internet.

**Comment by guylepage3** [comment]
Let's dissect why Apple's tagline for their famous ad and why it worked so well.. 

> "You'll see why 1984, won't be like 1984"
- The tagline contains the reference to George Orwell's 1984 fictionally oppressive government. (1984)
- It is an abstract way of saying.. "Life will change forever"
- It is highly mysterious..
- it is a passive way of executing push marketing
- it is easily digestible for all demographics
- evokes an extremely strong sense of passion and belief

Now let's take a look at the following taglines and what we are doing right and wrong;

> Declare your sovereignty. Be part of the free Internet.
> Freedom and prosperity. The new, decentralized Internet.
- Negative: These are not abstract and therefore are not mysterious. They are what they say they are.
- Negative: They are bold statements that some may find unbelievable. I want to come to the conclusion on my own. I don't want someone telling me "exactly" what to think. Give me something to think about.
- Positive: they are saying that they are wanting to evoke 
- Negative: By stating exactly what we want to evoke, we are, in these instances, almost turning the reader off as they may come across as to pushy.
- Negative: By being so narrow focused with the tagline we are automatically neglecting anyone that could possibly get excited about the idea of Blockstack that may not fit into that targeted demographic. What Blockstack has built is something ALL developers can rally behind. Let's give them that opportunity. I feel we can excite all devs with the right tagline/mission statement.

**Comment by shea256** [comment]
This was a line in a single commercial, though. It makes sense in context.

I could see something along the lines of what you came up with being used in a single campaign.

Though I still don't really get the line "live the future, be the future." Doesn't seem particularly interesting to me.

**Comment by guylepage3** [comment]
I'll grab a laundry list of taglines for you in a bit. they should be inspirational
- Drive better
- Just do it
- Think different
  etc..

**Comment by shea256** [comment]
Liberate yourself.

**Comment by guylepage3** [comment]
I like that direction much better.. :)

**Comment by guylepage3** [comment]
@shea256 

> Though I still don't really get the line "live the future, be the future." Doesn't seem particularly interesting to me.

Yeah, as stated, "I'd like to propose a new tagline discussion" it was only created to start a discussion/discovery to find strong messaging. :)

**Comment by guylepage3** [comment]
Issue moved to [blockstack/blockstack #91](https://github.com/blockstack/blockstack/issues/91) via [**ZenHub**](https://www.zenhub.com/)
