### ISSUE TITLE
Blockstack Swag!

### ISSUE THREAD

**Issue by guylepage3** [blockstack/community#28]
![swag_006](https://cloud.githubusercontent.com/assets/1711854/18767800/4cb31c4a-80ef-11e6-89b0-07ff31d3574f.gif)
## Want Blockstack Swag??

You've come to the right place.. 

**Types of Swag:**
- Blockstack Stickers
- Blockstack T-Shirts
- Blockstack Hoodies
- Blockstack Backpacks
## How do I receive my Blockstack Swag?
- Comment on this issue with the type of swag you want
- Then follow [twitter.com/blockstackorg](http://twitter.com/blockstackorg) and tweet at shoutout #BlockstackSWAG. 
- We'll then follow you back and gather the following information:
  - Item you're wanting
    - If a size is required, please include it. (PS. **XXL** is short for **I kick ass and crush it**)
  - First and Last name
  - Full postal address - exactly as your national post office would write it or it may not get delivered
  - Phone number
  - Email address

**Comment by shea256** [comment]
Albert Wenger wants a backpack and a hoodie.

**Comment by shea256** [comment]
Qasar Younis already has a sweatshirt and wears it every day (gross!) but he'd probably want a backpack too. I'll double check with him.

**Comment by guylepage3** [comment]
@shea256 maybe we should get Qasar 2-3 of them then? Great exposure for Blockstack.

**Comment by Skorpion7777** [comment]
Sebastian Pirozhkov

I've also already asked for stickers and a T-shirt. Now that you've added some items I would love to have a hoodie to. All in M.
Guylepage already has my address and everything.

Thanks a lot

**Comment by invix** [comment]
I'd like to get some stickers to pass around at the office, as well as maybe a hoodie, but not sure about putting in my name/address/phone in here publicly.

**Comment by guylepage3** [comment]
@invix yeah. I'll change the protocol for that now.

**Comment by guylepage3** [comment]
@invix updated the protocol for ordering Blockstack Swag.. Look forward to hearing from you and thanks again for the feedback.

**Comment by guylepage3** [comment]
Issue moved to [blockstack/blockstack #96](https://github.com/blockstack/blockstack/issues/96) via [**ZenHub**](https://www.zenhub.com/)
