### ISSUE TITLE
Design new blockstack architecture diagram

### ISSUE THREAD

**Issue by guylepage3** [blockstack/community#29]
Update blockstack core diagram to include Bittorrent

**Comment by guylepage3** [comment]
Complete!

![bsk-architecture-diagram](https://cloud.githubusercontent.com/assets/1711854/18934153/3541ee9a-85a6-11e6-9095-88c6caa18893.png)

**Comment by guylepage3** [comment]
@shea256, @muneeb-ali, @jcnelson, @larrysalibra 
Let me know if I'm missing anything on this new blockstack architecture diagram. Thx

**Comment by muneeb-ali** [comment]
Looks great to me! The only thing is "atlas DB" vs. zonefile DB because people won't know what Atlas is. I see Atlas more as an implementation for storing the zone files.

**Comment by shea256** [comment]
Two corrections:
- "Bittorrent" should be "BitTorrent" (that's how they capitalize the name)
- "Public Key" should be "Public key" (for capitalization consistency)

**Comment by shea256** [comment]
@muneeb-ali Yeah it could be reverted back to "zone file DB" to make it more clear what's being stored in there.

Also everyone please note that "zone file" should be used in lieu of "zonefile" to fit with the correct usage in the traditional domain name system.

**Comment by guylepage3** [comment]
![bsk-architecture-diagram2](https://cloud.githubusercontent.com/assets/1711854/18935392/c0e6290a-85ad-11e6-9ad8-582ba8709989.png)

**Comment by shea256** [comment]
Nice!

Would it be valuable to have "Bitcoin, Ethereum, Zcash" as examples of blockchains on the bottom?

This would make it clear that Blockstack is blockchain agnostic.

**Comment by guylepage3** [comment]
I feel it would be a great idea to add that..

**Comment by jcnelson** [comment]
+1 for multiple blockchains, but only if we can have a clean way of representing it.

I also liked John Light's suggestion (on Twitter) to add a "compute" layer, like applications, somewhere in the diagram.

**Comment by waynevaughan** [comment]
You can represent multiple blockchains by using long horizontal bars on the bottom of the diagram. I'll be forever grateful if you add WayneChain!

**Comment by guylepage3** [comment]
Haha!! WayneChain it is.. 😂

**Comment by shea256** [comment]
Yeah we could put an app layer above the storage layer.

The browser runs apps in this layer. Code and UI components are on the client and computation is done there.

Is that what you were thinking @jcnelson @john-light ?

**Comment by jcnelson** [comment]
either on top of storage, or to the left of the blockstack node (i.e. blockstack core is the "back-end" connection to the browser and apps).

**Comment by john-light** [comment]
@shea256 yes along those lines. since the browser is just one way that Blockstack apps could be delivered to users (as opposed to native/ standalone mobile/desktop apps) I think you could represent the "compute" layer as multiple devices (laptop, mobile phone, tablet, personal server) running the apps.

**Comment by shea256** [comment]
@jcnelson @john-light @guylepage3 We might actually need to have a clean separation between the clients and everything in this diagram.

The browser clients (both desktop and mobile) connect to a Blockstack Core node and resolve names to zone files and then to URIs and then to HTML files.

So the clients / the "compute layer" isn't really a layer in the same way the existing layers in the diagram are.

I do like the idea of clients to the left of the Blockstack Core node, connecting to the node. I also like the idea of a "layer" on top of the existing diagram, but with a visual distinction that shows that this is the frontend that connects to the backend and resolves names to apps via the virtualchain, routing, and storage layers.

**Comment by guylepage3** [comment]
@shea256 shall we add hyperledger to the list of blockchains?

**Comment by shea256** [comment]
I'm trying to figure out if hyperledger even is a blockchain. I heard from some people that it's actually a set of standards. @martindale @zmanian do you know the answer to this?

**Comment by zmanian** [comment]
Fabric and sawtoothlake are both blockchains.

Fabric uses a pluggable set of BFT consensus implementations. The most mature is a bog standard PBFT implementation.

Sawtooth lake uses PoET which leverages SGX to remotely attest ownership of a trusted Intel CPU.

**Comment by shea256** [comment]
OK great, thanks for the clarification @zmanian.

**Comment by zmanian** [comment]
Good doc on what Fabric is https://hyperledger-fabric.readthedocs.io/en/latest/abstract_v1/

**Comment by guylepage3** [comment]
Issue moved to [blockstack/blockstack #97](https://github.com/blockstack/blockstack/issues/97) via [**ZenHub**](https://www.zenhub.com/)
