### ISSUE TITLE
Blockstack YouTube banner is offset

### ISSUE THREAD

**Issue by john-light** [blockstack/community#34]
![blockstackytbanner](https://cloud.githubusercontent.com/assets/9424721/18936798/5d29dea6-859f-11e6-852a-b2282e060470.png)

https://www.youtube.com/channel/UCiyMoKVWkVdC_sC0CqrxCoQ

**Comment by guylepage3** [comment]
Thanks for the catch @john-light 

<img width="1086" alt="screenshot 2016-09-29 12 44 16" src="https://cloud.githubusercontent.com/assets/1711854/18963308/76ccb2cc-8642-11e6-99b6-c6e93ccc0413.png">

**Comment by guylepage3** [comment]
@shea256 we should delete this account as we currently have two youtube channels.
- https://www.youtube.com/channel/UCiyMoKVWkVdC_sC0CqrxCoQ

@john-light that was an old youtube channel. here's the new blockstack youtube channel.
- https://www.youtube.com/channel/UC3J2iHnyt2JtOvtGVf_jpHQ

**Comment by guylepage3** [comment]
@shea256 did you have a chance to delete this account? https://www.youtube.com/channel/UCiyMoKVWkVdC_sC0CqrxCoQ

**Comment by shea256** [comment]
@guylepage3 yeah it was deleted yesterday
