### ISSUE TITLE
Blockstack newsletter design

### ISSUE THREAD

**Issue by muneeb-ali** [blockstack/community#4]
@guylepage3 commented on [Wed Aug 17 2016](https://github.com/blockstack/marketing/issues/4)

Design a generic newsletter template for the community

Goals:
- bullets to current events
- footer links to;
  - reddit
  - blockstack.org
  - docs
  - twitter

**Comment by muneeb-ali** [comment]
@guylepage3 really looking forward to the newsletter!

**Comment by guylepage3** [comment]
Can you guys think of anything else we would like to have for requirements on this newsletter? Please note that there is another issue created for the [Blockstack announcement newsletter design](https://github.com/blockstack/community/issues/5)

**Comment by guylepage3** [comment]
Issue moved to [blockstack/blockstack #85](https://github.com/blockstack/blockstack/issues/85) via [**ZenHub**](https://www.zenhub.com/)
